name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # Chạy mỗi 5 phút
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render site
        run: curl -s -o /dev/null https://eden-batw.onrender.com/api/users
